services:

    gitserver:
        build:
            context: .
            dockerfile: Dockerfile.git
        working_dir: /var/www/
        ports:
            - "443:443"
            - "8000-8020:8000-8020"
            - "3000-3020:3000-3020"
        volumes:
            - git-bare:/var/www/git
            - git-data:/var/www/html
            - ssl-files:/etc/apache2/ssl/

volumes:
    git-bare:
        driver: local
    git-data:
        driver: local
    ssl-files:
        driver: local