services:

    gitserver:
        build:
            context: .
            dockerfile: Dockerfile.git
        working_dir: /var/www/html/dev_8001_org
        ports:
            - "443:443"
            - "8000:8000"
            - "3000:3000"

volumes:
    git-bare:
        driver: local
    git-data:
        driver: local